words = """
srASBpeThwTwhdZVPOaECJhGnxhRKzxrbMSDyGZGNZBbCOKvPpJKKaQEcoLGBfIi
KtpVsROccWwgrWdEqtNFskeDnFbfKWVEeLvtBUlWrOMgtxsaSkctfJQfdOGRNMze
BlFsCFafWXzvrGfazhEruTMOETzZRYnuHsrtHeYivQdXFnwdDslSSGpfOMyrhbgk
OnPiwDTzUBbRaJzGbvUGmVzzTPRaXmLZsXyElKjzwXUYUqiuggHiSzHiGSuQhgHT
ICVWIjVXMUXOQhPdEskSprJHQvvtRtNQEVUwkGGqDUrAXzWTMyUYIisiOxlTHcIs
FfSnhzmCgEwmoWChrqkyNdtdLFWErzlEprlTNZsPfedCDEsqvmLWmxgCxpmSPTjG
SxtXINfaDztBUNdiQWoaIgFkqajwhInhMzczvmTJjwgtSGGoIbozCJgVurJetNXS
XWeduNjPVlpZtDimsizGqUjaLjYWvlRdYdrWvHzNUnKOlAUpTBMkUNFqYLvQKoQi
PPwvndXenRCVaBotNEKkJPUrYnaWAgizfeHyQMoFICbCqKELTmUYvqPYpzKVBYPT
LxRLMyexgApRCWDjhQAsDQhRGStiyGMEAWoBLFpsdbGGxFbgIarMglYofcZXILlF
lCvkCkCXybTKiYrHLpWXbngLJyVIzhwPIqSQlHURyrrtBTUbyrmMEquLvVjfKrRz
TzVoiknxpIICbQGfptEtwvpvUkeqOvtCOuArDtavZFszWBStWtqEGLIdKuVMTFRX
hOWPpjHcEWmthjrKXEnfeNKDmPEyvneMQrDBGZdibvyCCFlfMFPsXhhADOZwmmoJ
kqsyNaPoKLuPsaLzvkpkVbRiAfOxsECFcuLWpfNPkfgIbpAuEXEoHLtrWtLJmHEM
IxsvZVryZQxcUgnZgDSlXjSroSBAiwpkqgiCVksMaVuhZpIqhDQglSmjUqYYAzQS
vorxlrNMeOYUFakgkhJfKQPBYKdSLYHKlcEWaqINpRgogVCQBAktVDZznrSikzvS
RmFCdJsaNSGnQZPPEZSizcsqcPMirBkJzFkVrVVNOlDSygFlmnjhcGuZdRVhTlsJ
mchZCQJUurVMEfaBDKqEfyXyzequOleOzwxDXxoXifpLtFbGtkyTbVSStjeSKviM
hjsuDVKrKOJYOgwIxLODEsHrMPyBWKRPfEugIYXXghDvyXPUBvSQPHRusscQDhax
mJnUnsfGHZANXdffxdeTLxvAuAPOcaSotONXBxiyFMSMUUpFGMYKWVFGttqfsNUD
fTIrWSVVeQhpvFRypLgpgIEuMssFOnCoNophSDWgFbIGpEkQbrPzWYlZLkcMWfoK
LNqbyJREvFRlwFbDViVIIvZUtQzolDSNdUiSKyGjTiGWyUqbXxTApqMkulpxgcYF
mzLnqDaWObWOVTkXoabkzrWaZUDyyTyndqAeJheDPOYuAnKwmUatXgcRRGekDvti
gtfLQHqVFJBrifkYlHdjUXLamveLrZpNbsEbQUvhArMkvClLdhHYyQNtxFIMFKri
MTJUeJowIEieTzdADsgnJFDgGwkRjUXQXxkLOUsYMcThlYixSicfCrhFcxUSFOMC
vsvyiimcnEGhRMcZKwxPHfAMcTCBEbhqoBdXHAyNSvVZwagTeImVWrcCpncCQGuW
xiGCPZErUvjrqIzQYSMAUnhCvNRoCdFOrLNoWtLVTHadALvCOISzdfKNfmXQbMvu
MfDfKDgNrQKZpxdjNZOdbxFuaGEpCeQslgaosqzUHJxEQftRLaWzuuRoTAdfeXjb
GjCOpLRnlLhVTNPnPhjDyWegbkvOzOFDYMYMhUndmlIzoCLOdMRBZoRxzVTUAIdX
ZigoLlmGUjLSoHSVdfEMdTXEUmiOITNsxVnXUWmNPfitzxAjBkuVMnluoOnUdqsw
yuCZozXoxAfRcWVMmblfcPPHfTLEkHXQnWyMQydLGhtsSgdCFiRSmvTJfkpLvLBW
IfwBjQTKxBiMlRTgNabJdxWIEFLVCdlqtSWUrmbASdXnXHBqtEbcUTgwvTHXdHRJ
yZzknQEBPxrYmwAXEgrsrUCqHyioVOYJuxpaNVeajeukkYAwEZsPzYcQPpWXvnNP
HivSHSSYVjlUndxAFpCxLoOtryvLvGniqvPzLBXAPWQgSccXINwfTiVFglMUtPRW
qfjorMQYyIUUJzrLLfxaTwfRcqdKDIfXZHCWJgYeRopRQtjGJjsTRrKamAgGMZKK
OpxyKUsnZVvhhNRAGaGwxZoiykvMaQjElxwgueWmTSJmoezRUegUBzElOdZNcdas
jzGoTXYzgVtVMRtVvswhfeFVUjPCcgeJXWyylbVzGigCHrNqOEdELTdiuZpaGGjY
PCeekznQSmdknmrzFvbPLIrbFcCVlUgCVpLOpcWdZjZamKFKrLXTkqjizSnaqFux
McLXPTbKNnWwkKBVlyqPfhvEHgXQehpOwriiwxGKvBFmmdOJNfMcCNWTAlOtLcMf
KXkgikyHqiouJoAIXeFImwmKCTabkRCVtAFdlwIQfDueyDobfjokxBkIiBCviViL
aWTFXHluvTMGqejeVkBAVmITjpvRgrCdSflpXRFWGaJlGMSPAOUvmdubXyweoVmd
nUOiMxgEvNKCalLwPPmNnMfOvtZOaPsdjfZecsDiHKXCyJCAGyklpOWfTvsrDSbS
GgWdNFsTrzQYkMOuDNTrgXFKJBloEClUJQgRqWgUeTmkogUwcAhDhGGCBSWxtXmL
jmJFjtKURtTCxNOoEbYYuvKpwXSNUKvCzOXJomxxcltzWbUDymejntiPbtwJkjjL
YQfgYrGYFUCtaiClkbYEhoNSPsMxLlMZcMJQvOgkEZoyBDJIuhafgcEIapXAQVgS
biJvUDHTwppEkmWWFeuCaqWFRhlCfTLpXVjnKFcTEXgkpZxQxobkpdWoaFOZtbyG
DVFAjxmQohapTLsnlKjIgZrFsBgMqBnbaHelrDeWuEwqvkvYzbPgqvoWyKZeGlJR
LyhbETrzTEWbTgjbrUtbKnDgEaQeuTLzZsaMCMMvjwbpDKoSgPLVUKpzaQgjdKui
ipcvbOibcxRAAaNQScbbyqnxrTcRnHJgmrYICLhdBXvXeGbfAEXOaABYdxFqtKpX
VMQpHXLtxCVMlxDJPUlJNOGvzFMyIRBFiEeSIejdBlyPArQERlKuEhYUGJirKvQe
fZLqUQXskRnbzUrwPLzstPxISsjLuFzsmfxziVesrSkEDNjepgVPUbHLGwtKIsyy
jVQHxPHjdWdWQMaQwtZIBkChEAetDyBJeTtgzYHUURveRLLScKUhSJMoAXtrYgkd
XGISnnAHvQtezKRKwaMmHajgEJZoWznEiZLZSsGLDGhxnEjpubPPxNLjCkbfYdGX
UpXiTfaTaSDFnsHKWNzMqgxBBOshEWBowWCFkDCWvkWoTKMnEgjNopURJjwafPQo
LNGBMAuCItMGZBoqiEUjeiosNsmYqJtGvpFgXWcCCKdRRvDihdYcTQheshcTUuSs
vQWmwtaokIjaLbPmgBexZQFRIKAqvwbuXUNkbyMyseXBnZHfhUsFGSkRqYZVKTal
ohbMXsghRUDuysSMwFmPmMWFxCpISMWxIFEQSWtqqkumZGoANSOasHgJBEKwLJBx
EnhhbwqqUcrqynAATewLteSGXPCwYfVQgGXtTpIbwSYrxBQGdxJMzfqRYDPKFPNy
rqefGfSzBgzRDvLHSyXTRTXFOIqiyBpFexQDXBePJNDPpBicIRTBBtLquAlxYUWp
uDbvmJSOjpnEGIWxgcbFdzzSKwnauiAxOvjjWULAdOMBtgOTcIayliaGytvVbZvV
myBWAJyqYcTnHUXyInpLaeIJceCyyBfIMUXXDGrKJadafwwQkVSKlWKGPjPFZDcW
NIhleRaIXHDiIImdQPftZvZtwYxYcuOCffEypBzRtscpuqMwxGZvycKtevNJPBdu
BXIUSUooGgYgRtGaZTyrCGbkjFGxbRMDQGzxiGZDjcHWfOrQkJJGuJTRIGiKOBYS
RTiouiAZWvhAWiSDDwTicHgvehsUtDftgBIJUMxLNHlvxBoFPceuOwqRdiELVybA
OaWlrcBjVkJcxYPJpgIJGngjyUvFdnDCDBqxqmRYlIhDkyqhGbWbZoAOXpmALQzE
waahgMSlsrOajPlGSIKFUsyRDjPQcOoqJtjvNPLiHJECIFuhiieZyMJcQTckUhsc
JMuVdEziMfEgOmrHvuvivgMBeRRpLgkwwopLkRQIWJRZbYOsxrotLbudGLwgkKWA
NWwIwJNQdCVoBSiPnxjeHknuhsXcxDccrSnByzvXBUOAetHRQYyvqGLxWbwXYdrB
fSBcNOSJhGTNscIAXpCLoACaQgcBTXzGtCiDnGLaZCWxIfwKdyJwbkxdeUjzpQrL
wasIKLSLFMErfKPxQyQfiRYhhuxScwVlqzgsMlZuyoaFCuhMjIVDOeBHdkZYudad
MChXqyiKUmkAPRPWSgdmNagCsooVpScswCenpBoCCjqXpBbDEhhvUVTfSLhgtKhA
SwGouuQeDzyjoXuxELQAmkVnGAAJxMahkARslprzGtdbkPrcXyhWwhWrrXXPRfKm
jjNEYgHtmwctNbqrCUaJppplPnJETEyDbrmleiKLkgLJMuBpRlWIfeOoQCbGNOVm
lMtZgYCGmsLcTkBvHJGUzlgyUjyXoNopRHMJeaHIcjRuXiLjagnhHjxSlJtVmgGR
nvktdojVhHxwZvjieJCppvkavHWPcnbZtiMnvygAkBjiGBNmlrAYuaHkjwCoIszH
mGONXqaxwJZVqOgquGAkJEXUnLtCdyrQwDGGOuuUUHWpraStbFMSYGrOSNLxLeNl
VeTJkksolsMhVeuQRLjUdAmKJlwecCiHTuspPtVxUVzzVDuvPvWNquPLIhVdpUQV
uiIGiYcfUANgHnoWQMSoQOMHlqNIkvQbgoqhHzfvcLpIyoxHIaxdLrZJgXAijynL
vXEIaAizXcUiTPlaBhdpjYZeoaCHcrYUznynHPJpoPpgEKxjaAZlgpxjsnhNsQSP
jRXzgygsNDuWnjCqnPLJJGkibUXGsPgUxZAwhYBWCdsQPWvtbcvDQRdXMxBMdVRX
LpHGufsTQPXOloFIZkfDljsUUUxCiNQoYfuLwDNUzcrjIOSrMoWVmmHNynFbukYX
EFLIpBfedpFjGHfXqYVuZbUnUjDLsWYrEVCKmvqQVaatsRnUosnABsmXrfvVMVTX
itiYWUKtcdnZpYuGPPqoQrpDFmVuxMTknZQwOjhwElrfYDFKtbGvVszNbtDNpbFH
AKKUFHZVuXRaRYeKWucYqXLiwoNvNBYXnaQZBTVGWIDGTaWfBrMrVVkyaXjotYYS
QxzajEoWWcoJxlBwSxGODjsUeomYxHpuEpDylwYjndIsrwyyfAGyMVSxPtgttvWT
fbstfMfCYrlFismGkAZvqbSnisILDcSlugVwbBkwAXopthpjqFbToNDuMccnEdSR
ByociaMtlbAVesZqEaHGNFaDenFwGWiGAqTOCSnXnSzneVjmHVeNBGuoOmMgcbgJ
BCpQPYmbHdkJPQdBlAmLLsgueEfLNGnZJFqfzkONnDHxIuJDMbUNoVwSFBBJwrHi
jsTMSqNsFPdjAXraRKgEDqDHWGzqWzrWpLwaUpuiguxpaxhIkPdjLCqOMhrYrLjy
oCsNawRNcHSXhjtKNgMhYohRFIYQJfspJOmybuPhuQjRwNQeESRWPgJKhzrNdzbQ
iQbNfSIAViBdewwSDRaTKvZpbtThjYASfTUCIIhZQtxEoTlJsvTZQwalTTBgqLpf
syitrvwmKCJoZWOnQSZTpDlXEsInyeNyTaZYpvZPDBygFDGEztjPzVZDHtRKoTgZ
ELUgEwsMyzfOsQEZNnsCvKWxckBddrMwfWUbjjHTvQvParGEFmxCCkQLcoabKjyo
kUpJyQnmkNDbNrOJdpUanzuTbzRkpcoFjhKhjqWqzmnfOlTjVoDpWFpjOEYbLPio
IwfqoEtPAazEhmYsNmSsfsTIwOzrtggXhDkjPokcDUcfOZjnqauuzJOnRaOJhvPq
DmUhnfrbHEcdfcaOLxxQbDePIzwqHMonfDlDqDAhazrhGJtxVuPDPZVnhJHSGBpm
VFvahyuyKrpqvsTNSQxEbmssKJbYQkbXwsnAqZjSYPqDcrfORmttBvwUBPYIxLlm
zeoMaelsCbImrasxwfFfFZdHeUdIRZKjMnNeneArMvLngyGjmcaowYiCctrIqUjA
WwLaPFtBJGhHEhbVqJNIdKAGMPOltZIKEEBQTQhfvdiAHJeZMifwPMxTEHJqkgmH
MmYPYqCarDoZerLtHgyWwJjeIlSYlISWvPrSciUXvxKSqWLKTRcWUURClgXyqQXW
QvOWXTLUrziKQRjxTpnwRNQaYMIMMUXcTZrEGGhFXmmaaHZZmQIeQGBHoRjgAAZa
jnziDKkxziRrTuAsAEObpbwYDUcuILWFEuMsBcPwwMNdCeFNSDjbGvDYUOuPpLem
tqLOlvxLPFnMYnCtssijrLQdoWsuereycVPkjVbtavKEAnlcJVzHruIoeWBcuydL
eYyDLYeyYMOUtroZiGJRHRnLiSBLuGUNlzZLnhiWTdNGrlAVPoLoYsmTTLlpKdLq
wnSxMIDXBHAxYeMrpyoNjvjlyPflmlOsLWtrmShLYMSRjhXkxrgwGaIXBuCWRxCg
euWyuIUSQqPwKMhHSBdFsYZKOsqZXXAVxXXJKFCniGXeQzNBbkEkcqowQgqhTuiP
EyUFjarTkkFHDOuhLHUzZfxLwHIooIGkNPAXexdNwIuqSoSBhDeQLkPLiRuQMubH
SqIgunJsBWHLBFsUoTNjZWQDDxEtAQNDYAdeiGpjEBVGIDGLvdMiECXnuielRZau
FRBSmnpoGJhHCdavVKiYEOWLLAVcUzocBdkPaPCuvhWXUQSuAsgIBQAoROBzlGta
MIHsHoWxPqBvFCosnqLmfGeZazRxTiHWdwXAthYuAIdPSgbpuIVvROExXuhhvCcC
mnxfGaqiJNNvzHbEWUlpgLyJHlRBFgPPJCaIAFkAlyqdwBfgdYRcoQGXZLvlsmMD
xekdcmQIqBQVRGvHtYUzthgAtyrZvigUMkaDPIGSIFjzCkKJhEONIkRxkoPXAGmw
BmHVpvPdwRaDGmTverKrwSsVLvfIjGMubztrSpnGdlFRbxgmhNeOjcMPFoApwePl
gRabyllXdlTerRBKdbvYgqNDYYNchlwdWwyLlvQBOVIHfJlFVtmkDvinYkkeRJks
cztzEKQsFOSmPnVgSNqSqndAVQJnnlqhJLbtxPZbxfYRRaCyWMCKfORKWGnjClFi
xcIQspwUWtrlJSiCZvKzdaIQturxnBGdLIREHDldUCdNdxnsHrClqLATvPhoZRti
xXiQYejsarnKOoYIifvLeGISmmeQNCMAkqLxRQrnEkmgFLCNCjWCtrDMEIfczvJg
tlGWDsTbSEUKvWEIhOhMszkXUCcVhACkLKQJqSxkujXpTshKYRmuadwaBQSvkIPF
RPtDaSYvgJXxmsHFngRdxiQFgCugHlKOWXpJeTkDWuZhzFKedytKzEuUQDiJmwkY
UvDYZpTWshnJdBlZmnoTKgcwFrasjBpQyPTAKPDBFPfLzCepkPTHTQAqVMMFXUun
EgOjOyrcsbIZzPEREiymQYmBjiDtYCjAJVIQgHlhvYvLFXRjJwejJegVjoycbVqE
vxKEdkLrFsoMxWeKBcHeMLcIvtZXXTJOXhpzaiMBTjBHVsOgNWzbRfAbAiNeEBpW
nysbeNbuRpTRCAYWKcqcnzXWkRWvlVtHjwSObEWanCJSLrwZoBpNiTSTYntvJJZN
CNspCFDqQnAMMqpvPQWtbpsaMwzECdxXcKbbeQkskLALCZrzCNfdYOxEayHHkRNF
"""

# prep work
words = words.split("\n")
words = "".join(words)       
words = [letter for letter in words]

# main work
def holding_qualifies(holding):
    # if it contains lowercaseUPPERCASE
    first = "".join(holding[:4])
    second = "".join(holding[4:])

    if first.islower() and second.isupper():
        return first == second.lower()
    return False


qualified = []

holding = words[:8]

index = 8

while index < len(words):
    if holding_qualifies(holding):
        qualified.append(holding)
    else:
        holding.pop(0)
        holding.append(words[index])
        print(holding)

    index += 1

print(qualified)
